# @credits: https://stackoverflow.com/a/67059629
on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'CI'
        git config --global user.email 'bot@noreply.github.com'
        git commit -am "Auto updated submodules" && git push || echo "No changes to commit"

    - name: Install, build, and upload your site
      uses: withastro/action@v0
      with:
        package-manager: npm  # cry about it https://i.imgur.com/AFdIEgc.png

  deploy:
    needs: sync
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
