# @credits: https://stackoverflow.com/a/67059629
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'CI'
        git config --global user.email 'bot@noreply.github.com'
        git commit -am "Auto updated submodules" && git push || echo "No changes to commit"
